### PR TITLE
Add GenTX for StakeLab

### PR DESCRIPTION
**Pull request by zdeadex**

### CODE REVIEW

**Comment by jhernandezb** [comment]
Could you move the file to cygnusx-1/gentx/ folder?

**Comment by zdeadex** [comment]
Ive done a new one following the new documentation

Le jeu. 8 juil. 2021 à 16:31, Jorge Hernández ***@***.***> a
écrit :

**Comment by jhernandezb** [comment]
@zdeadex  you would need to remove the one in bellatrix-1 folder and just have 1 file in the PR.

**Comment by zdeadex** [comment]
done

Le ven. 9 juil. 2021 à 20:45, Jorge Hernández ***@***.***> a
écrit :

**Pull request merged**
